### ISSUE TITLE
iOS safari playback issues

### ISSUE THREAD

**Issue by emranemran** [livepeer/catalyst#120] opened 2022-08-19 21:36 UTC
Reported by @ericxtang. 

On mobile safari: 
``` 
Playback defaults to lowest bitrate, and doesn’t move up the bitrate ladder.

The video has a “pulsating” visual artifact.

Cold cache load time varies btw 2s and 10s, with occasional timeouts.
```

**Comment by yondonfu** [comment] 2022-08-22 19:57
From @Thulinma 

> The iOS issues (well, the first two, anyway) are non-issues: the pulsating effect is the result of how we transcode (needs a transcoding config change to fix) and the bit rate not going up is the result of slow delivery (iOS clients use download speeds for segments to figure out if they can go to a higher quality or not).

I think it would make sense to tackle these two issues one by one:

- First, see if we can repro the "lowest bitrate issue" - if the player is not defaulting the lowest bitrate for someone with plenty of bandwidth then that just re-affirms Jaron's point that that the player is just defaulting to the bitrate that is most appropriate given how fast it can currently download segments and then there is a good chance that the original report was caused by the player being unable to download segments quickly enough (low bandwidth?) causing the lowest bitrate to be the default. If the player *does* default to the lowest bitrate despite plenty of bandwidth being available then there is likely a deeper issue to investigate
- Then, we can see if we can repro the "pulsating" visual artifact and then change the transcoding configuration to get playback that does not have the artifact

**Comment by iameli** [comment] 2022-08-31 10:20
This does appear to be a regression, unfortunately — got side-by-side livepeer.studio and livepeer.fun streams, and this is a common result:
![image.png](https://images.zenhubusercontent.com/58fe9bf551aa2c30577c54e2/05249eea-b78f-4a78-bff0-9decdfe4d8b7)

**Comment by iameli** [comment] 2022-08-31 10:24
Gotta be related to the fact that segment download times are way, way faster on the old system (left old right new)

![image.png](https://images.zenhubusercontent.com/58fe9bf551aa2c30577c54e2/25fc4657-c4a2-4f2d-b56c-62d0c48ad37d)

Which is in turn probably related to the fact we're booting up a new MistOutHLS per stream. Filing that now, previous discussion is here https://discord.com/channels/423160867534929930/900210676591652985/1007052633577639968

**Comment by iameli** [comment] 2022-09-01 11:15
Fixed by https://github.com/DDVTECH/mistserver/commit/ba108f6fb52c57412626026cb95b1a9be0bc06bc

There was a problem related to blocking output on the last (most recent) segment present in an HLS playlist. This change excludes the last segment from the playlist, fixing this problem at the cost of one segment of latency. We can revisit this when we want to try and flip LL-HLS back on.

**Closed by iameli** 2022-09-01 11:15 UTC
Labels: bug, critical
